export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export const GET_CATEGORY_LIST = "GET_CATEGORY_LIST";
export const GET_PRODUCT_BY_CATEGORY = "GET_PRODUCT_BY_CATEGORY";
export const ERRORS = "ERRORS";
